#! /usr/bin/env python2.7

# Public Domain (-) 2008-2012 The Espra Authors.
# See the Espra UNLICENSE file for details.

"""Build script for Proto Espra."""

from cStringIO import StringIO
from hashlib import sha1
from inspect import getargspec
from json import loads as decode_json
from os import chmod, listdir, mkdir, remove, stat
from os.path import dirname, exists, join, realpath, splitext
from shutil import rmtree
from sys import argv, exit, platform
from time import sleep
from urllib import urlopen
from zipfile import ZipFile

from plumbum import FG, local
from plumbum.cmd import ant, assetgen
from yaml import load as load_yaml

# ------------------------------------------------------------------------------
# Print Utilities
# ------------------------------------------------------------------------------

def error(msg):
    print "\033[1;31m!! ERROR: %s !!\033[0m" % msg
    exit(1)

def start(msg):
    print "\033[1;34m>> %s\033[0m" % msg

def progress(msg):
    print "\033[1;30m## %s\033[0m" % msg

def success(msg):
    print "\033[32m** %s\033[0m" % msg

# ------------------------------------------------------------------------------
# Platform Detection
# ------------------------------------------------------------------------------

if platform.startswith('darwin'):
    PLATFORM = 'darwin'
elif platform.startswith('linux'):
    PLATFORM = 'linux'
else:
    error("The %r operating system isn't currently supported" % platform)

# ------------------------------------------------------------------------------
# File Handling
# ------------------------------------------------------------------------------

def get_yaml_conf(filename):
    f = open(join(dirname(__file__), filename), 'rb')
    conf = load_yaml(f)
    f.close()
    return conf

def read(filename):
    f = open(filename, 'rb')
    data = f.read()
    f.close()
    return data

# ------------------------------------------------------------------------------
# Global Constants
# ------------------------------------------------------------------------------

META = get_yaml_conf('meta.yaml')

GAE_SDK_FILES = {
    'java': "appengine-java-sdk-%s.zip" % META['gae-version'],
    'go': "go_appengine_sdk_%s_amd64-%s.zip" % (PLATFORM, META['gae-version']),
    'python': "google_appengine_%s.zip" % META['gae-version']
}

GAE_SDK_PATH_ROOT = "http://googleappengine.googlecode.com/files/"
SCRIPT_ROOT = dirname(__file__)

# -----------------------------------------------------------------------------
# Command Decorator
# -----------------------------------------------------------------------------

COMMANDS = {}

def register(func):
    COMMANDS[func.__name__.replace('_', '-')] = (getargspec(func), func)

# ------------------------------------------------------------------------------
# Utility Functions
# ------------------------------------------------------------------------------

def get_path(*path):
    return join(SCRIPT_ROOT, *path)

# ------------------------------------------------------------------------------
# Download Handlers
# ------------------------------------------------------------------------------

def download_gae_sdk(runtime):

    name = "%s App Engine SDK" % runtime.title()
    filename = GAE_SDK_FILES[runtime]
    target_dir = get_path('.appengine_%s_sdk' % runtime)
    version_file = join(target_dir, 'VERSION')

    if runtime == 'java':
        if exists(join(
            target_dir, 'lib', 'user',
            'appengine-api-labs-%s.jar' % META['gae-version']
            )):
            success("%s is up-to-date." % name)
            return
    elif exists(version_file):
        sdk_version_file = open(version_file, 'rb')
        sdk_version = sdk_version_file.readline().split()
        sdk_version = sdk_version and sdk_version[-1] or ''
        sdk_version_file.close()
        if sdk_version == '"%s"' % META['gae-version-name']:
            success("%s is up-to-date." % name)
            return

    start("Installing %s" % name)

    if exists(target_dir):
        progress("Removing Existing %s %s" % (name, sdk_version))
        rmtree(target_dir)

    progress("Downloading %s..." % name)

    try:
        req = urlopen(GAE_SDK_PATH_ROOT + filename)
        if runtime == 'go':
            checksum = META['go-%s-sdk' % PLATFORM]
        else:
            checksum = META['%s-sdk' % runtime]
        sdk_file = validate_download(req, checksum)
    except Exception, err:
        error("Couldn't Download the %s: %r" % (name, err))

    progress("Extracting %s" % name)
    try:
        mkdir(target_dir, 0777)
        sdk_zip = ZipFile(sdk_file)
        for iname in sdk_zip.namelist():
            newname = iname.split("/", 1)
            if len(newname) != 2:
                continue
            newname = newname[1]
            if not newname:
                continue
            if iname.endswith('/'):
                mkdir(join(target_dir, newname))
            else:
                target_path = join(target_dir, newname)
                newfile = open(target_path, 'wb')
                newfile.write(sdk_zip.read(iname))
                newfile.close()
                info = sdk_zip.getinfo(iname)
                if info.external_attr:
                    chmod(target_path, info.external_attr >> 16)
    except Exception, err:
        error("Couldn't Extract the %s: %r" % (name, err))

    success("%s Successfully Installed." % name)

def install_dist():

    dist_path = get_path("dist")
    if exists(dist_path):
        if exists(join(dirname(realpath(dist_path)), ".git")):
            success("A version controlled `dist` directory exists.")
            return

def validate_download(req, checksum):
    data = req.read()
    if sha1(data).hexdigest() != checksum:
        error("Mismatched checksum for downloaded file")
    return StringIO(data)

# ------------------------------------------------------------------------------
# Build
# ------------------------------------------------------------------------------

class BuildInfo(object):
    pass

def build(info, raise_exit):

    progress("Running assetgen")
    if info.profile:
        with local.cwd(SCRIPT_ROOT):
            assetgen["assetgen.yaml", "--profile", info.profile] & FG
    else:
        with local.cwd(SCRIPT_ROOT):
            assetgen["assetgen.yaml"] & FG

    build_dir = info.build_dir
    cache = info.cache
    changed = 0
    template_dir = info.template_dir
    templates = info.templates

    filepath = info.assets_path
    statinfo = stat(filepath)
    if (filepath not in cache) or (cache[filepath][0] < statinfo.st_mtime):
        changed = 1
        contents = read(filepath)
        cache[filepath] = (statinfo.st_mtime, contents)
        assets = dict(
            (str(k), str(v)) for k, v in decode_json(contents).iteritems()
            )
        info.assets = assets
        info.init_css = read(join(build_dir, assets['init.css']))
        info.init_js = read(join(build_dir, assets['init.js']))

    filepath = info.config_path
    statinfo = stat(filepath)
    if (filepath not in cache) or (cache[filepath][0] < statinfo.st_mtime):
        changed = 1
        info.config = get_yaml_conf(filepath)
        cache[filepath] = (statinfo.st_mtime, None)

    for filename in listdir(template_dir):
        if filename.startswith('.'):
            continue
        filepath = join(template_dir, filename)
        statinfo = stat(filepath)
        if (filepath not in cache) or (cache[filepath][0] < statinfo.st_mtime):
            changed = 1
            contents = read(filepath)
            cache[filename] = (statinfo.st_mtime, contents)
            templates[splitext(filename)[0]] = contents

    if not changed:
        return

    changed = 0
    html_mtime = info.html_mtime
    if not html_mtime:
        changed = 1
    else:
        for value in cache.itervalues():
            if value[0] > html_mtime:
                changed = 1

    if not changed:
        return

    data = info.config.copy()
    data['assets'] = info.assets
    data['init.css'] = info.init_css
    data['init.js'] = info.init_js

    progress("Generating templates")

    output = [
        '// DO NOT EDIT.\n',
        '// Auto-generated templates file.\n\n',
        'package espra\n\n',
        ]
    out = output.append

    for tmpl in sorted(templates):
        contents = data['template/' + tmpl] = templates[tmpl] % data
        if tmpl.startswith('_'):
            continue
        out("var html%sStr = `%s`\n\n" % (tmpl.title(), contents))

    progress("Generating html.go")

    output[-1] = output[-1][:-1]
    f = open(info.html_path, 'wb')
    f.write(''.join(output))
    f.close()

# ------------------------------------------------------------------------------
# Core Tasks
# ------------------------------------------------------------------------------

@register
def app(profile='', watch=False):
    """build the app files"""

    start("Building app files")

    info = BuildInfo()
    info.assets_path = get_path("assets.json")
    info.build_dir = get_path("app", "build")
    info.cache = {}
    info.config_path = get_path("etc", "app", "config.yaml")
    info.html_path = html_path = get_path("app", "espra", "html.go")
    info.profile = profile
    info.template_dir = get_path("etc", "template")
    info.templates = {}

    if exists(html_path):
        info.html_mtime = stat(html_path).st_mtime
    else:
        info.html_mtime = 0

    try:
        while 1:
            build(info, not watch)
            if not watch:
                break
            start("Sleeping ...")
            sleep(1)
    except KeyboardInterrupt:
        exit(0)

    success("App files successfully built")

@register
def clean():
    """remove built app files"""

    start("Removing built app files")

    html_path = get_path("app", "espra", "html.go")
    if exists(html_path):
        progress("Removing html.go")
        remove(html_path)

    with local.cwd(SCRIPT_ROOT):
        progress("Running assetgen --clean")
        assetgen["assetgen.yaml", "--clean"] & FG

    success("Built files successfully removed")

@register
def deploy(app):
    """deploy a production build"""

    start("Deploying %s" % app)

    all = 0
    if app == 'all':
        all = 1

    if all or app == 'python':
        progress("Deploying the Python app")
        appcfg = local[get_path(".appengine_python_sdk", "appcfg.py")]
        with local.cwd(get_path("python")):
            appcfg["update", "."] & FG

    if all or app == 'java':
        progress("Building the Java app")
        with local.cwd(get_path("java")):
            ant["war"] & FG
        progress("Deploying the Java app")
        appcfg = local[get_path(".appengine_java_sdk", "bin", "appcfg.sh")]
        with local.cwd(get_path("java")):
            appcfg["update", "war"] & FG

    success("Finished deploying %s" % app)

@register
def install():
    """install the various dependencies"""

    for runtime in ('go', 'java', 'python'):
        download_gae_sdk(runtime)

    install_dist()

@register
def run(profile='dev'):
    """build and run a local instance"""

    start("Running servers under the %s profile" % profile)

# -----------------------------------------------------------------------------
# Script Runner
# -----------------------------------------------------------------------------

if __name__ == '__main__':
    argv = argv[1:]
    if not argv or argv[0] in ('-h', '--help', 'help'):
        out = []
        print "Usage: build [command]\n"
        print "Commands:\n"
        for cmd in sorted(COMMANDS):
            spec, func = COMMANDS[cmd]
            if spec.args:
                extra = "/%s" % '/'.join("<%s>" % arg for arg in spec.args)
            else:
                extra = ""
            out.append(("%s%s" % (cmd, extra), func.__doc__))
        max = 0
        for name, _ in out:
            spacing = len(name)
            if spacing > max:
                max = spacing
        max += 5
        for name, doc in out:
            pad = (max - len(name)) * ' '
            print "\t%s%s%s" % (name, pad, doc)
        print
        exit(0)
    for cmd in argv:
        cmd = cmd.split('/', 1)[0]
        if cmd not in COMMANDS:
            error("Couldn't find the %s command" % cmd)
    for cmd in argv:
        args = cmd.split('/')
        cmd = args.pop(0)
        spec, func = COMMANDS[cmd]
        slen = len(args)
        req = len(spec.args)
        if slen > req:
            error("The %s command only takes %d arguments" % (cmd, req))
        if spec.defaults:
            req -= len(spec.defaults)
        if slen < req:
            error("The %s command requires at least %d arguments" % (cmd, req))
        func(*args)
